export const HRC2_TPHH_CONSTANT = {
    'Al Binder': 'nhomThoi',
    'AlCubes13': 'nhomThoi',
    'AlCubes50': 'nhomThoi',
    'Anthracite': 'than',
    'Burnt dolo': 'dolomite',
    'Burnt lime': 'voi',
    'Burnt Lime_': 'voi',
    'CaF2': 'huynhThach',
    'Carbon': 'chatTangC',
    'Coke': 'thanCoke',
    'Cu_Lance Tip': 'cu',
    'FDSlag': 'xi',
    'FeCr MC': 'feCr',
    'FeCrHC': 'feCr',
    'FeMn HC': 'hcFeMn75',
    'FeMn MC': 'feMn',
    'FeNb': 'feMb',
    'FeP': 'feP',
    'Ferro_Phosphorus': 'feP',
    'FeSi': 'feSi',
    'FeSi 73': 'feSi',
    'FeTi70': 'feTi',
    'FeTiWire': 'dayFeTi',
    'Iron Ore': 'quangFe',
    'NiMetal': 'niken',
    'Pure Ca Wire': 'dayCaDac',
    'SiMn LC': 'siMn',
    'SiMn MC': 'siMn',
    'CaAl Wire': 'dayCaAl',
    'Quartzite' : 'quaczit',
    'CaSi Wire': 'dayCaSi',
    'Al Wire': 'dayAl',
    'AlWire': 'dayAl',
    'FeV': 'feV',
    'FeSiAl': 'feSiAl'
}